name: download_models_for_maird
services:
    vllm-openai:
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ${PWD}/.cache/huggingface:/root/.cache/huggingface
        ports:
            - 8791:8000
        env_file:
            - path: ${PWD}/vllm/.env
        image: vllm/vllm-openai:v0.6.3
        command: --model meta-llama/Llama-3.2-1B-Instruct --max-model-len=512 --gpu-memory-utilization=0.5 --served-model-name=Llama-3.2-1B-Instruct
    infinity:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ${PWD}/.cache:/app/.cache
        ports:
            - 8792:7997
        image: michaelf34/infinity:0.0.70-nvidia-torch25
        command: v2 --model-id=jinaai/jina-embeddings-v3 --model-id=jinaai/jina-reranker-v2-base-multilingual --url-prefix=/v2